### ISSUE TITLE
login Story

### ISSUE THREAD

**Issue by Yazanwolf** [RefugeesCodeAT/rc-store#10]
Business justification:
    • as a user I want to be able to login
    • so that I can use the application
Acceptance criteria:
    • given a valid user name and password in the login page
    • when I click the login button
    • then I will be redirected to the home page

    • Given the user name or password were wrong
    • then I will be redirected to the login page, with an error message
Clarification:
    • user is stored in the database with the role user (the database should be already existed)
Estimation:
	3 points

**Comment by fozatkardouh** [comment]
Done.
we now have user and admin login with error msgs
