### ISSUE TITLE
Display items story

### ISSUE THREAD

**Issue by Yazanwolf** [RefugeesCodeAT/rc-store#12]
Business justification:
    • As a logged in user
    • I want to be able to see all the items in the store
    • So that I can see their related details

Acceptance criteria:
    • given a logged in user
    • when I am in the home page
    • then I will see all items with their details

    • Given a booked item
    • I want to see button called ‘’booked by’’
    • If I click on it
    • I want to see the borrowing info

    • Given an available item 
    • I want to see a button called ‘’view’’
    • When I click on it
    • I want to see a pop up with the item info
    • And two inputs: from - till
    • And a button says ‘’book’’

    • Given that the button “book” is clicked
    • I want to book the item according to the date I’ve selected

Clarifications:
    • The item info are: name, description, image, borrowing limit
    • The borrowing info are: booked by (name of borrower), due date
Estimation:
	5 points

**Comment by fozatkardouh** [comment]
will start creating junits for this story

**Comment by fozatkardouh** [comment]
Story Done.
added junit5 to confirm it
