### ISSUE TITLE
My item’s story

### ISSUE THREAD

**Issue by Yazanwolf** [RefugeesCodeAT/rc-store#13]
Business justification:
    • As a logged in user
    • I want to be able to see all the items that I am borrowing
    • So that I see a button besides each item which says ‘’return’’
Acceptance criteria:
    • Given a logged in user
    • When I am in ‘’my items’’ page
    • Then I want to see all the items currently booked by me
    • When clicked on item
    • I want to see the description and a button says return

    • Given that return button is clicked
    • Then the item is marked as returned
    • And the info in the webpage is updated
Clarifications:
    • The description should contain: name, description, date of borrow, due date
Estimation:
	5 points

**Comment by fozatkardouh** [comment]
this is a closed story.
Tested by junit5
