### ISSUE TITLE
Add item’s story

### ISSUE THREAD

**Issue by Yazanwolf** [RefugeesCodeAT/rc-store#14]
usiness justification:
    • As a logged in admin
    • I want to see the items page
    • And an extra button called ‘’add item’’
    • So that I can add a new item to the items table
Acceptance criteria:
    • Given a logged in admin
    • When I am in ‘’home’’ page
    • Then I want to see an extra button says ‘’add item’’
    • When I click on it
    • I want to be redirected to a page called ‘’add item’’
    • So that I can be able to add an item, with it’s information
Clarifications:
    • The item’s information should contain: item name, description, image, borrowing limit
    • The admin is a pre-existed user, created when the application starts
Estimation:
	5 points

**Comment by fozatkardouh** [comment]
done all of this
