### ISSUE TITLE
Users Data base

### ISSUE THREAD

**Issue by Yazanwolf** [RefugeesCodeAT/rc-store#16]
• there should be a database which contains the user’s info.
• user’s info in the database contains: first and last name, password, E-mail, list of roles and ID.
• there should be a preexisted user called Admin has the role user and
admin.

**Comment by fozatkardouh** [comment]
Done with this.
I created the admin account in the database.
I created the User model and connected it to the User document in the database.
The User model will look like this, and these information will be used in the JSON transmission to the frontend:

String id;
String firstName;
String lastName;
String email;
String password;
Set<String> roles = new HashSet<>();
