### ISSUE TITLE
Login Endpoint

### ISSUE THREAD

**Issue by Yazanwolf** [RefugeesCodeAT/rc-store#18]
• login needs E-mail, and password
• the given E-mail and password should be checked if right
• in case of unsuccessful login → redirect to login page
• there should be a notification in case login was unsuccessful
• when login is successful → redirect to home page

**Comment by fozatkardouh** [comment]
Done!
the front end will send me a JSON file that contains these info:
String email
String password
They will be checked against our database if valid. If yes, a Boolean of True will be sent back.
If no, a Boolean of False will be sent back.

The api to be used for this operation is : /login and the method is POST

**Comment by fozatkardouh** [comment]
update:
we are now using the spring security and the spring login endpoints.
spring login page is also being used.
