### ISSUE TITLE
Display item page

### ISSUE THREAD

**Issue by Yazanwolf** [RefugeesCodeAT/rc-store#22]
• the page is the home page
• all the items should be viewed with their details
• if the item is booked → there should be a button called “booked by”
• if clicked on → there should be viewed the borrowing information:
- booked by (name of borrower)
- due date
• if the item is available → there should be a button called “view”
• if clicked on→ a pop up should appear with the item’s info, two input
(from till) and a button called “book”
• the item’s info are:
- name
- description
- image
- borrowing limit

**Comment by fozatkardouh** [comment]
done.
view all items, and a button called view next to each one.
when u click on it, it will redirect you to a new page in which you can either book it from and to a date of your choosing.
and if not available, you will be shown all the borrower’s info
