### ISSUE TITLE
Items Database

### ISSUE THREAD

**Issue by Yazanwolf** [RefugeesCodeAT/rc-store#23]
• there should be a table for items
• the item’s info are:
- name
- description
- ID- Boolean “is borrowed”
- Date of borrow
- Due date
- Name of borrower
- Image
- Borrowing limit

**Comment by fozatkardouh** [comment]
done.
the Item class (model) has all the relative info:

name
description
ID- Boolean “is borrowed”
Date of borrow
Due date
Name of borrower
Image
Borrowing limit
