### ISSUE TITLE
Display items Endpoint

### ISSUE THREAD

**Issue by Yazanwolf** [RefugeesCodeAT/rc-store#24]
• view all:
- there should be a “view all” endpoint
- it shows all the items in the store with the needed information
• book one:
- update all the information of the received item in the database
- change it’s “is booked” boolean to true
- create an entry in the log table (see log for more info)

**Comment by fozatkardouh** [comment]
done.
we now have a view all page at ("/") and the html pages is called home
next to each item in this page, there is a button which takes you to the itme html page at the location ("/iteminfo/{id}"), where u can see all the information about this item.
if taken, you will see all the borrow info.
if not, you will be able to book it for yourself.

the log entry will be dealt with later with the log story
